devsearch/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path("projects/", include('projects.urls'), name="projects"),
    path("", include('users.urls'), name="profile"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.projects_view, name='projects'),
    path('project/<str:pk>/', views.project_view, name='project'),
    path('create-project/', views.create_project_view, name='create_project'),
    path('update-project/<str:pk>/', views.update_project_view, name='update_project'),
    path('delete-project/<str:pk>/', views.delete_project_view, name='delete_project'),




]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

    path('', views.profiles_view, name='profiles'),
    path('profile/<str:pk>/', views.user_profile_view, name='user_profile'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    description = models.TextField(null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('UP', 'Up Vote'),
        ('DOWN', 'Down Vote'),
    )
    # owner =
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=500, null=True, blank=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    github = models.CharField(max_length=200, blank=True, null=True)
    website = models.CharField(max_length=200, blank=True, null=True)
    linkedin = models.CharField(max_length=200, blank=True, null=True)
    youtube = models.CharField(max_length=200, blank=True, null=True)
    twitter = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.name

projects/views.py
from django.shortcuts import render, redirect
from .models import Project
from .froms import ProjectForm
from django.contrib.auth.decorators import login_required


def projects_view(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'projects/projects.html', context)


def project_view(request, pk):
    project = Project.objects.get(id=pk)
    # tags = project.tags.all()
    context = {
        'project': project,
        # 'tags': tags,
    }
    return render(request, 'projects/single-project.html', context)


@login_required(login_url="users:login")
def create_project_view(request):
    form = ProjectForm()

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')

    context = {
        'form': form,
    }
    return render(request, 'projects/projects-form.html', context)


@login_required(login_url="users:login")
def update_project_view(request, pk):

    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects:projects')

    context = {
        'form': form,
    }
    return render(request, 'projects/projects-form.html', context)


@login_required(login_url="users:login")
def delete_project_view(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == "POST":
        project.delete()
        return redirect('projects:projects')
    context = {
        'object': project
    }
    return render(request, 'projects/delete-template.html', context)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Profile


def login_view(request):

    if request.user.is_authenticated:
        return redirect('users:profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('users:profiles')
        else:
            messages.error(request, 'Username or Password is incorrect')

    return render(request, 'users/login_register.html')


def logout_view(request):
    logout(request)
    messages.error(request, 'User was logged out!')
    return redirect('users:login')


def profiles_view(request):
    profiles = Profile.objects.all()
    context = {
        'profiles': profiles
    }
    return render(request, 'users/profiles.html', context)


def user_profile_view(request, pk):
    profile = Profile.objects.get(id=pk)
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description="")

    context = {
        'profile': profile,
        'top_skills': top_skills,
        'other_skills': other_skills
    }
    return render(request, 'users/user-profile.html', context)

projects/templates/projects/delete-template.html
{% extends 'base.html' %}
{% block content %}
    <h1>Project Form</h1>

    <form action="" method="post">
    {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button>
            <a href="{% url 'projects:projects' %}">Go Back</a>
        </button>


        <input type="submit" value="Confirm">

    </form>
{% endblock %}

projects/templates/projects/projects-form.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>
                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Input:Text -->
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit"/>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
    <main class="projects">
        <section class="hero-section text-center">
            <div class="container container--narrow">
                <div class="hero-section__box">
                    <h2>Search for <span>Projects</span></h2>
                </div>

                <div class="hero-section__search">
                    <form class="form" action="#" method="get">
                        <div class="form__field">
                            <label for="formInput#search">Search By Projects </label>
                            <input class="input input--text" id="formInput#search" type="text" name="text"
                                   placeholder="Search by Project Title"/>
                        </div>

                        <input class="btn btn--sub btn--lg" type="submit" value="Search"/>
                    </form>
                </div>
            </div>
        </section>
        <!-- Search Result: DevList -->
        <section class="projectsList">
            <div class="container">
                <div class="grid grid--three">
                    {% for project in projects %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'projects:project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{ project.featured_image.url }}"
                                         alt="project thumbnail"/>
                                    <div class="card__body">
                                        <h3 class="project__title">{{ project.title }}</h3>
                                        <p><a class="project__author" href="{% url 'users:user_profile' project.owner_id %}">By {{ project.owner.name}}</a></p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Positive
                                            Feedback ({{ project.vote_total }}
                                            Vote{{ project.vote_total | pluralize:"s" }})
                                        </p>
                                        <div class="project__tags">
                                            {% for tag in project.tags.all %}
                                                <span class="tag tag--pill tag--main">
                                                    <small>{{ tag }}</small>
                                                </span>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

projects/templates/projects/single-project.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
    <main class="singleProject my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <h3 class="singleProject__subtitle">Tools & Stacks</h3>
                    <div class="singleProject__toolStack">
                        {% for tag in project.tags.all %}
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>{{ tag }}</small>
                            </span>
                        {% endfor %}
                    </div>
                {% if project.source_link %}
                	<a class="singleProject__liveLink" href="{{project.source_link}}" target="_blank"><i class="im im-external-link"></i>Source
                        Code
                    </a>
                {% endif %}
                {% if project.demo_link %}
                	<a class="singleProject__liveLink" href="{{project.demo_link}}" target="_blank"><i class="im im-external-link"></i>Live Demo
                    </a>
                {% endif %}

                </div>
                <div class="column column--2of3">
                    <img class="singleProject__preview" src="{{ project.featured_image.url }}"
                         alt="portfolio thumbnail"/>
                    <a href="{% url 'users:user_profile' project.owner_id %}" class="singleProject__developer">{{ project.owner }}</a>
                    <h2 class="singleProject__title">{{ project.title }}</h2>
                    <h3 class="singleProject__subtitle">About the Project</h3>
                    <div class="singleProject__info">
                        {{ project.description }}
                    </div>

                    <div class="comments">
                        <h3 class="singleProject__subtitle">Feedback</h3>
                        <h5 class="project--rating">
                            {{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }}
                            Vote{{ project.vote_total | pluralize:"s" }})
                        </h5>

                        <form class="form" action="#" method="POST">
                            <!-- Textarea -->
                            <div class="form__field">
                                <label for="formInput#textarea">Comments: </label>
                                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                                          placeholder="Write your comments here..."></textarea>
                            </div>
                            <input class="btn btn--sub btn--lg" type="submit" value="Comments"/>
                        </form>
                        <div class="commentList">
                            <div class="comment">
                                <a href="profile.html">
                                    <img class="avatar avatar--md"
                                         src="https://pbs.twimg.com/profile_images/1335382240931368961/b3wSZKj4_400x400.jpg"
                                         alt="user"/>
                                </a>
                                <div class="comment__details">
                                    <a href="profile.html" class="comment__author">Sulamita Ivanov</a>
                                    <p class="comment__info">
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit alias
                                        numquam perferendis
                                        mollitia minus minima exercitationem possimus ab deserunt qui, soluta iusto
                                        doloribus eveniet
                                        similique consequuntur ratione, dignissimos ut magni laborum quo.
                                    </p>
                                </div>
                            </div>
                            <div class="comment">
                                <a href="profile.html">
                                    <img class="avatar avatar--md"
                                         src="https://avatars.githubusercontent.com/u/33843378" alt="user"/>
                                </a>
                                <div class="comment__details">
                                    <a href="profile.html" class="comment__author">Dennis Ivanov</a>
                                    <p class="comment__info">
                                        Consectetur adipisicing elit. Reprehenderit alias numquam perferendis mollitia
                                        minus minima
                                        exercitationem possimus ab deserunt qui, ratione, dignissimos ut magni laborum
                                        quo.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css"/>
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}"/>
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}"/>

    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
{% include 'navbar.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<hr>
<h1>Footer</h1>

templates/navbar.html
{% load static %}
<!-- Header Section -->
<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'users:profiles' %}" class="header__logo">
            <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo"/>
        </a>
        <nav class="header__nav">
            <input type="checkbox" id="responsive-menu"/>
            <label for="responsive-menu" class="toggle-menu">
                <span>Menu</span>
                <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
                <li class="header__menuItem"><a href="{% url 'users:profiles' %}">Developers</a></li>
                <li class="header__menuItem"><a href="{% url 'projects:projects' %}">Projects</a></li>
                <li class="header__menuItem"><a href="">Inbox</a></li>

                {% if request.user.is_authenticated %}
                    <li class="header__menuItem"><a href="{% url 'projects:create_project' %}">Add Project</a></li>
                    <li class="header__menuItem"><a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a></li>
                {% else %}
                    <li class="header__menuItem"><a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign
                        Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

users/templates/users/login_register.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username"/>
        <input type="password" name="password" placeholder="Enter password"/>
        <input type="submit" value="Login"/>
    </form>
{% endblock %}

users/templates/users/profiles.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
    <main class="home">
        <section class="hero-section text-center">
            <div class="container container--narrow">
                <div class="hero-section__box">
                    <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                    <h2>FROM AROUND THE WORLD</h2>
                </div>

                <div class="hero-section__search">
                    <form class="form" action="#" method="get">
                        <div class="form__field">
                            <label for="formInput#search">Search Developers </label>
                            <input class="input input--text" id="formInput#search" type="text" name="text"
                                   placeholder="Search by developer name"/>
                        </div>

                        <input class="btn btn--sub btn--lg" type="submit" value="Search"/>
                    </form>
                </div>
            </div>
        </section>
        <!-- Search Result: DevList -->
        <section class="devlist">
            <div class="container">
                <div class="grid grid--three">
                    {% for profile in profiles %}
                        <div class="column card">
                            <div class="dev">
                                <a href="{% url 'users:user_profile' profile.id %}" class="card__body">
                                    <div class="dev__profile">
                                        <img class="avatar avatar--md" src="{{ profile.profile_image.url }}"
                                             alt="image"/>
                                        <div class="dev__meta">
                                            <h3>{{ profile.name }}</h3>
                                            <h5>{{ profile.short_intro|slice:"60" }}</h5>
                                        </div>
                                    </div>
                                    <p class="dev__info">{{ profile.bio|slice:"150" }}</p>
                                    <div class="dev__skills">
                                        {% for skill in profile.skill_set.all|slice:"6" %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{ skill }}</small>
                                             </span>
                                        {% endfor %}
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>
{% endblock %}

users/templates/users/user-profile.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Section -->
    <main class="profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}"/>
                            <h2 class="dev__name">{{ profile.name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            <p class="dev__location">Based in {{ profile.location }}</p>
                            <ul class="dev__social">
                                {% if profile.github %}
                                    <li>
                                        <a title="Github" href="{{ profile.github }}" target="_blank"><i
                                                class="im im-github"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.youtube %}
                                    <li>
                                        <a title="Youtube" href="{{ profile.youtube }}" target="_blank"><i
                                                class="im im-stackoverflow"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.twitter %}
                                    <li>
                                        <a title="Twitter" href="{{ profile.twitter }}" target="_blank"><i
                                                class="im im-twitter"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.linkedin %}
                                    <li>
                                        <a title="LinkedIn" href="{{ profile.linkedin }}" target="_blank"><i
                                                class="im im-linkedin"></i></a>
                                    </li>
                                {% endif %}
                                {% if profile.website %}
                                    <li>
                                        <a title="Personal Website" href="{{ profile.website }}" target="_blank"><i
                                                class="im im-globe"></i></a>
                                    </li>
                                {% endif %}

                            </ul>
                            <a href="#" class="btn btn--sub btn--lg">Send Message </a>
                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">{{ profile.bio }} </p>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Skills</h3>
                        <div class="devInfo__skills">
                            {% for skill in top_skills %}
                                <div class="devSkill">
                                    <h4 class="devSkill__title">{{ skill.name }}</h4>
                                    <p class="devSkill__info">{{ skill.description }}</p>
                                </div>
                            {% endfor %}

                            <h3 class="devInfo__subtitle">Other Skills</h3>
                            <div class="devInfo__otherSkills">
                                {% for skill in other_skills %}
                                    <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill.name }}</small>
                </span>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                    <div class="devInfo">
                        <h3 class="devInfo__title">Projects</h3>
                        <div class="grid grid--two">
                            {% for project in profile.project_set.all %}
                                <div class="column">
                                    <div class="card project">
                                        <a href="{% url 'projects:project' project.id %}" class="project">
                                            <img class="project__thumbnail" src="{{ project.featured_image.url }}"
                                                 alt="project thumbnail"/>
                                            <div class="card__body">
                                                <h3 class="project__title">{{ project.title }}</h3>
                                                <p><a class="project__author"
                                                      href="{% url 'users:user_profile' profile.id %}">By {{ project.owner }}</a>
                                                </p>
                                                <p class="project--rating">
                                                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span>
                                                    Positive
                                                    Feedback ({{ project.vote_total }}
                                                    Vote{{ project.vote_total|pluralize:"s" }})
                                                </p>
                                                <div class="project__tags">
                                                    {% for tag in project.tags.all %}
                                                     <span class="tag tag--pill tag--main">
                                                        <small>{{ tag }}</small>
                                                     </span>
                                                        {% endfor %}
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}